version: '3'
services:
  web:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/myapp'
    tty: true
    stdin_open: true
    depends_on:
      - db
    links:
      - db
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
  db:
    image: mysql:8.0
    volumes:
      - 'mysql_data:/var/lib/mysql'
      - './docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d'
    environment:
      - 'MYSQL_DATABASE=myapp_development'
      - 'MYSQL_ROOT_PASSWORD=pass'
      - 'MYSQL_USER=webapp'
      - 'MYSQL_PASSWORD=webapp_password'
    command: '--default-authentication-plugin=mysql_native_password'
    ports:
      - '4306:3306'
volumes:
  mysql_data:
